[package]
name = "pm2ls-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
websocket = "0.24.0"
cpal = "0.13.4"
ringbuf = "0.2.6"
audiopus_sys = "0.2.1"